Vamos explorar dados de crédito presentes no arquivo credito.xlsx. Os dados estão no formato de Excel (XLSX) e contém informações sobre clientes de uma instituição financeira. Em especial, estamos interessados em explicar a segunda coluna, chamada de default, que indica se um cliente é adimplente (default = 0), ou inadimplente (default = 1), ou seja, queremos entender o porque um cliente deixa de honrar com suas dívidas baseado no comportamento de outros atributos, como salário, escolaridade e movimentação financeira. Uma descrição completa dos atributos está abaixo

In [1]:
import pandas as pd

In [10]:
#Para ler as informações do excel
tabela = pd.read_excel('credito.xlsx')
tabela.head()

,id,default,idade,sexo,dependentes,escolaridade,estado_civil,salario_anual,tipo_cartao,meses_de_relacionamento,qtd_produtos,iteracoes_12m,meses_inativo_12m,limite_credito,valor_transacoes_12m,qtd_transacoes_12m
0,768805383,0,45,M,3,ensino medio,casado,$60K - $80K,blue,39,5,3,1,12691.51,1144.90,42
1,818770008,0,49,F,5,mestrado,solteiro,menos que $40K,blue,44,6,2,1,8256.96,1291.45,33
2,713982108,0,51,M,3,mestrado,casado,$80K - $120K,blue,36,4,0,1,3418.56,1887.72,20
3,769911858,0,40,F,4,ensino medio,na,menos que $40K,blue,34,3,1,4,3313.03,1171.56,20
4,709106358,0,40,M,3,sem educacao formal,casado,$60K - $80K,blue,21,5,0,1,4716.22,816.08,28

In [9]:
tabela.shape

(10127, 16)

In [6]:
tabela.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       10127 non-null  int64
 1   default                  10127 non-null  int64
 2   idade                    10127 non-null  int64
 3   sexo                     10127 non-null  object
 4   dependentes              10127 non-null  int64
 5   escolaridade             10127 non-null  object
 6   estado_civil             10127 non-null  object
 7   salario_anual            10127 non-null  object
 8   tipo_cartao              10127 non-null  object
 9   meses_de_relacionamento  10127 non-null  int64
 10  qtd_produtos             10127 non-null  int64
 11  iteracoes_12m            10127 non-null  int64
 12  meses_inativo_12m        10127 non-null  int64
 13  limite_credito           10127 non-null  float64
 14  valor_transacoes_12m     10127 non-null  float64
 15  qtd_transacoes_12m       10127 non-null  int64
dtypes: float64(2), int64(9), object(5)
memory usage: 1.2+ MB

In [7]:
tabela.columns

Index(['id', 'default', 'idade', 'sexo', 'dependentes', 'escolaridade',
       'estado_civil', 'salario_anual', 'tipo_cartao',
       'meses_de_relacionamento', 'qtd_produtos', 'iteracoes_12m',
       'meses_inativo_12m', 'limite_credito', 'valor_transacoes_12m',
       'qtd_transacoes_12m'],
      dtype='object')

In [16]:
tabela_pessoa = tabela[['id','sexo','idade','estado_civil','default']]
tabela_pessoa.head()

          id sexo  idade estado_civil  default
0  768805383    M     45       casado        0
1  818770008    F     49     solteiro        0
2  713982108    M     51       casado        0
3  769911858    F     40           na        0
4  709106358    M     40       casado        0

In [31]:
tabela_pessoa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10127 non-null  int64
 1   sexo          10127 non-null  object
 2   idade         10127 non-null  int64
 3   estado_civil  10127 non-null  object
 4   default       10127 non-null  int64
dtypes: int64(3), object(2)
memory usage: 395.7+ KB

In [51]:
dado_pessoa = []
#iterrows foi usado para passar pelas outras linhas
for id, dado in tabela_pessoa.iterrows():
  if (dado['default'] == 1 and dado['estado_civil'] == 'solteiro'):
    #feito um dicionário para colocar na planilha
    dado_pessoa.append({'id': dado['id'], 'sexo': dado['sexo'], 'idade': dado['idade']})

#converter dicionário para DataFrame
dado_pessoa = pd.DataFrame(dado_pessoa)

In [54]:
dado_pessoa.shape

(668, 3)

In [57]:
#Converte para csv só se estiver em DataFrame
dado_pessoa.to_csv('credito.csv')